base_images:
  base:
    name: "4.7"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-openshift-4.6
images:
- context_dir: roots2i
  dockerfile_path: Dockerfile
  from: base
  inputs:
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/build-test-images/roots2i/.
  to: test-build-roots2i
promotion:
  name: "4.7"
  namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.7"
  namespace: ocp
zz_generated_metadata:
  branch: master
  org: openshift
  repo: build-test-images
